export const LANGUAGES = [
  "🇬🇧 English",
  "🇫🇷 French",
  "🇦🇫 Dari",
  "🇦🇱 Albanian",
  "🇩🇿 Algerian Arabic",
  "🇦🇩 Andorran Catalan",
  "🇦🇴 Angolan Portuguese",
  "🇦🇬 Antiguan English",
  "🇦🇷 Argentine Spanish",
  "🇦🇲 Armenian",
  "🇦🇼 Aruban Dutch",
  "🇦🇺 Australian English",
  "🇦🇹 Austrian German",
  "🇦🇿 Azerbaijani",
  "🇧🇸 Bahamian English",
  "🇧🇭 Bahraini Arabic",
  "🇧🇩 Bangladeshi Bengali",
  "🇧🇧 Barbadian English",
  "🇧🇾 Belarusian",
  "🇧🇪 Belgian Dutch",
  "🇧🇪 Belgian French",
  "🇧🇿 Belizean English",
  "🇧🇯 Beninese French",
  "🇧🇹 Bhutanese Dzongkha",
  "🇧🇴 Bolivian Spanish",
  "🇧🇦 Bosnian Bosnian",
  "🇧🇼 Botswanan English",
  "🇧🇷 Brazilian Portuguese",
  "🇻🇬 British Virgin Islands English",
  "🇧🇳 Bruneian Malay",
  "🇧🇬 Bulgarian",
  "🇧🇫 Burkinabe French",
  "🇧🇮 Burundian French",
  "🇰🇭 Cambodian Khmer",
  "🇨🇲 Cameroonian French",
  "🇨🇦 Canadian English",
  "🇨🇦 Canadian French",
  "🇨🇻 Cape Verdean Portuguese",
  "🇨🇫 Central African French",
  "🇹Ꭰ Chadian Arabic",
  "🇨🇱 Chilean Spanish",
  "🇨🇳 Chinese Mandarin",
  "🇨🇴 Colombian Spanish",
  "🇰🇲 Comorian Comorian",
  "🇨🇬 Congolese French",
  "🇨🇩 Congolese Swahili",
  "🇨🇷 Costa Rican Spanish",
  "🇨🇮 Ivorian French",
  "🇭🇷 Croatian Croatian",
  "🇨🇺 Cuban Spanish",
  "🇨🇿 Czech",
  "🇩🇰 Danish",
  "🇩🇯 Djiboutian Arabic",
  "🇩🇲 Dominican English",
  "🇩🇴 Dominican Spanish",
  "🇪🇨 Ecuadorian Spanish",
  "🇪🇬 Egyptian Arabic",
  "🇸🇻 Salvadoran Spanish",
  "🇬🇶 Equatorial Guinean Spanish",
  "🇪🇷 Eritrean Tigrinya",
  "🇪🇪 Estonian Estonian",
  "🇪🇹 Ethiopian Amharic",
  "🇫🇰 Falkland Islands English",
  "🇫🇴 Faroese Faroese",
  "🇫🇯 Fijian English",
  "🇫🇮 Finnish",
  "🇫🇷 French",
  "🇬🇦 Gabonese French",
  "🇬🇲 Gambian English",
  "🇬🇪 Georgian",
  "🇩🇪 German",
  "🇬🇭 Ghanaian English",
  "🇬🇷 Greek",
  "🇬🇱 Greenlandic Greenlandic",
  "🇬🇩 Grenadian English",
  "🇬🇺 Guamanian English",
  "🇬🇹 Guatemalan Spanish",
  "🇬🇳 Guinean French",
  "🇬🇼 Guinea-Bissauan Portuguese",
  "🇬🇾 Guyanese English",
  "🇭🇹 Haitian Haitian Creole",
  "🇭🇳 Honduran Spanish",
  "🇭🇰 Hong Kong Cantonese",
  "🇭🇺 Hungarian",
  "🇮🇸 Icelandic Icelandic",
  "🇮🇳 Indian Hindi",
  "🇮🇩 Indonesian",
  "🇮🇷 Iranian Persian",
  "🇮🇶 Iraqi Arabic",
  "🇮🇪 Irish",
  "🇮🇱 Israeli Hebrew",
  "🇮🇹 Italian",
  "🇯🇲 Jamaican English",
  "🇯🇵 Japanese",
  "🇯Ο Jordanian Arabic",
  "🇰🇿 Kazakh Kazakh",
  "🇰🇪 Kenyan English",
  "🇰🇮 Kiribati English",
  "🇰🇵 North Korean Korean",
  "🇰🇷 South Korean Korean",
  "🇰W Kuwaiti Arabic",
  "🇰🇬 Kyrgyz Kyrgyz",
  "🇱🇦 Lao",
  "🇱🇻 Latvian Latvian",
  "🇱🇧 Lebanese Arabic",
  "🇱🇸 Lesotho Sesotho",
  "🇱🇷 Liberian English",
  "🇱🇾 Libyan Arabic",
  "🇱🇮 Liechtenstein German",
  "🇱🇹 Lithuanian",
  "🇱🇺 Luxembourgish",
  "🇲🇬 Malagasy Malagasy",
  "🇲🇼 Malawian English",
  "🇲🇾 Malaysian Malay",
  "🇲🇻 Maldivian Dhivehi",
  "🇲🇱 Malian French",
  "🇲🇹 Maltese Maltese",
  "🇲🇭 Marshallese Marshall",
  "🇲🇲 Burmese Burmese",
  "🇲🇳 Mongolian Mongolian",
  "🇲🇪 Montenegrin Montenegrin",
  "🇲🇦 Moroccan Arabic",
  "🇲🇿 Mozambican Portuguese",
  "🇲🇲 Burmese Burmese",
  "🇳🇦 Namibian English",
  "🇳🇵 Nepali",
  "🇳🇱 Dutch",
  "🇳🇿 New Zealand English",
  "🇳🇮 Nicaraguan Spanish",
  "🇳🇪 Nigerian English",
  "🇳🇴 Norwegian Bokmål",
  "🇳🇴 Norwegian Nynorsk",
  "🇴🇲 Omani Arabic",
  "🇵🇰 Pakistani Urdu",
  "🇵🇦 Panamanian Spanish",
  "🇵🇬 Papua New Guinean English",
  "🇵🇾 Paraguayan Spanish",
  "🇵🇪 Peruvian Spanish",
  "🇵🇭 Philippine Tagalog",
  "🇵🇱 Polish",
  "🇵🇹 Portuguese",
  "🇶🇦 Qatari Arabic",
  "🇷🇪 Réunion French",
  "🇷🇴 Romanian",
  "🇷🇺 Russian",
  "🇷🇼 Rwandan French",
  "🇰🇳 Saint Kitts and Nevis English",
  "🇱🇨 Saint Lucian English",
  "🇻🇨 Saint Vincent and the Grenadines English",
  "🇼🇸 Samoan Samoan",
  "🇸🇲 Sammarinese Italian",
  "🇸🇹 São Tomé and Príncipe Portuguese",
  "🇸🇦 Saudi Arabian Arabic",
  "🇸🇳 Senegalese French",
  "🇷🇸 Serbian Serbian",
  "🇸🇨 Seychellois French",
  "🇸🇱 Sierra Leonean English",
  "🇸🇬 Singaporean English",
  "🇸🇰 Slovak",
  "🇸🇮 Slovenian",
  "🇸🇧 Solomon Islands English",
  "🇸🇴 Somali Somali",
  "🇿🇦 South African English",
  "🇿🇦 South African Afrikaans",
  "🇪🇸 Spanish Spain",
  "🇱🇰 Sri Lankan Sinhala",
  "🇸🇩 Sudanese Arabic",
  "🇸🇷 Surinamese Dutch",
  "🇸🇿 Swazi Swati",
  "🇸🇪 Swedish",
  "🇨🇭 Swiss German",
  "🇨🇭 Swiss French",
  "🇨🇭 Swiss Italian",
  "🇸🇾 Syrian Arabic",
  "🇹🇼 Taiwanese Mandarin",
  "🇹🇯 Tajik Tajik",
  "🇹🇿 Tanzanian Swahili",
  "🇹🇭 Thai",
  "🇹🇱 Timorese Tetum",
  "🇹🇬 Togolese French",
  "🇹🇰 Tokelauan Tokelauan",
  "🇹🇴 Tongan Tongan",
  "🇹🇹 Trinidadian English",
  "🇹🇳 Tunisian Arabic",
  "🇹🇷 Turkish",
  "🇹🇲 Turkmen Turkmen",
  "🇹🇻 Tuvaluan Tuvaluan",
  "🇺🇬 Ugandan English",
  "🇺🇦 Ukrainian",
  "🇦🇪 United Arab Emirates Arabic",
  "🇺🇾 Uruguayan Spanish",
  "🇺🇿 Uzbek Uzbek",
  "🇻🇺 Vanuatu Bislama",
  "🇻🇪 Venezuelan Spanish",
  "🇻🇳 Vietnamese",
  "🇿🇲 Zambian English",
  "🇿🇼 Zimbabwean English",
];
